name: Sonar

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Cache global .gradle folder
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: global-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.kt*') }}-${{ hashFiles('**/*.java') }}
        restore-keys: |
          gradle-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Run sonar task
      run: ./gradlew sonarqube --no-daemon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
